language: ruby

cache: bundler

rvm:
  - 2.0.0-p598
  - 2.2.0
  - jruby-1.7.20
  - jruby-9.0.0.0

env:
  global:
    - NSQ_DOWNLOAD=nsq-0.3.5.linux-amd64.go1.4.2.tar.gz
    - JRUBY_OPTS="--server -J-Dfile.encoding=utf8 --2.0"

install:
  - wget https://s3.amazonaws.com/bitly-downloads/nsq/$NSQ_DOWNLOAD
  - tar zxvf $NSQ_DOWNLOAD.tar.gz
  - export PATH=$NSQ_DOWNLOAD/bin:$PATH
  - $NSQ_DOWNLOAD/bin/nsqd --data-path=/tmp &
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rspec

notifications:
  email:
    recipients:
      - aemadrid@gmail.com
    on_success: change
    on_failure: change

sudo: false